### ISSUE TITLE
waybar not clickable on top screen pixel since cedde21 

### ISSUE THREAD

**Issue by yorickvP** [swaywm/sway#3546]
Steps to reproduce:
`sway & WAYLAND_DISPLAY=wayland-1 waybar`, then move the cursor out of screen over a waybar button.

Expected behavior: button should stay active, so that there is an infinitely big hitbox.
Actual behavior: top pixel does not hit waybar buttons.

I bisected this to cedde21c967ae5be0d1a9c7656ab8c6b3186ae42 (#3516)

**Comment by eternal-sorrow** [comment]
Actually any application inconsistently responds to clicks made in 1 pixel from screen boundary.

**Comment by yorickvP** [comment]
It's also hard to bring up the firefox nav bar in fullscreen.

**Comment by RedSoxFan** [comment]
Can you replicate on master? This might have been fixed by https://github.com/swaywm/sway/pull/3694.

**Comment by naibaf0** [comment]
It seems to work for me now in regards to clicking for example the workspace buttons with the top-most pixel row.

However occasionally going to the most right pixel column in firefox (wayland) and scrolling still won't work for me.

**Comment by RedSoxFan** [comment]
> However occasionally going to the most right pixel column in firefox (wayland) and scrolling still won't work for me.

I can only replicate with firefox and the same behavior occurs with both the x11 and wayland backends for firefox and occurs under weston and i3 as well. I'm not sure if that's a bug or intended behavior for firefox, but it is consistent across the board and has nothing to do with sway.

I'm going to close this as fixed by #3694.
