### ISSUE TITLE
Popup clicks don't work when popup is drawn over another container 

### ISSUE THREAD

**Issue by pedrocr** [swaywm/sway#4381]
* Sway Version: sway version 1.1-rc1-80-ge4bba906 (Jul 27 2019, branch 'master')
* Debug Log: https://gist.github.com/pedrocr/535e2380a303660c426505e56b489de6
* Configuration File: default

When a popup is over another container, clicks on menu items don't work. To reproduce use firefox or a gnome-terminal with tabs and right-click on a tab such that the popup opens over the container to the right. Clicking a menu item will then not work over the other container but will work over the parent container. The situation is something like this:

![popup](https://user-images.githubusercontent.com/246322/61993920-24637d80-b06b-11e9-81fd-18534583493c.png)

Clicking on "Close Terminal" works over the parent container but not over the other container on the right.

I tested this with 1.0 and 1.1.1 as well, using wlroots 0.5 and 0.6. All of them are broken but in 1.0 nothing happens when you click. With 1.1.1 and master when you click it's as if the mouse has left and reentered the popup as the highlight over the menu item being hovered disappears and reappears.

**Comment by human9** [comment]
I can reproduce on sway 1.2-rc1-15-g84417119. When a popup menu is outside of a window's frame, it becomes unclickable, but only under certain circumstances (always only when using native wayland backends).

In the case of GTK programs like gnome-terminal, changing the window to floating mode fixes the issue (off-window popups clickable). This also works with similarly affected GTK applications like evince, nemo, and xfce4-terminal.

Qt applications are also affected, but floating the windows doesn't help. Examples: Okular and Qt5 Designer.

But this behaviour only ever happens when the programs are using their native wayland backend: 
i.e. set GDK_BACKEND=x11 and all GTK programs are fixed, QT_QPA_PLATFORM=xcb and Qt programs are fixed, MOZ_ENABLE_WAYLAND=0 and Firefox is fixed.

**Comment by Mel34** [comment]
Based on my tests @versusvoid's patch doesn't fix the issue: part of the popup surface that's over the other container is still unclickable. Tested with firefox and some gtk3 programs (gedit, lutris).

**Comment by versusvoid** [comment]
Unfortunately, I can't reproduce problem with my patch.

**Comment by Mel34** [comment]
env: https://gist.github.com/Mel34/1ffbd417ffe99abce166d45703f242e8
sway config: https://gist.github.com/Mel34/ab9b6d562f9181ed8bbdc7c76022b85b

**Comment by Mel34** [comment]
@versusvoid I'm sorry for the noise on this issue, your commit does fix it. I've compiled it without ccache and it started working after that.

**Comment by philipflohr** [comment]
I can still reproduce the described behavior.

my setup is:

- sway 1.4
- affected app is Linphone (QT) run from flatpak (XWayland client)

The incoming call popup is only clickable if either the popup is on the applications container or if I set 

> for_window [class="linphone"] floating enable

in the sway configuration file.

**Comment by Darapsas** [comment]
Same is happening with `google-chrome`, on:

```bash
❯ uname -r
5.14.12-zen1-1-zen

❯ pacman -Q sway
sway 1:1.6.1-1
```
