### ISSUE TITLE
XDG_RUNTIME_DIR is not set in the environment (new Arch installation, with Sway)

### ISSUE THREAD

**Issue by brianbecsi** [swaywm/sway#7202]
Hello! New user here.

I have a fresh Arch install which I installed using ``archinstall``. I try to run Sway but I get some errors that there was no backend able to open a seat [libseat/libseat.c:79]. I try to sudo but I get an error XDG_RUNTIME_DIR not set. I tried running ``sudo -E sway`` but get the error "unable to drop root ... refusing to start".

Appreciate any help with this I don't know my way around X display.

**Comment by beatplucker** [comment]
Hi there. 
You should add yourself to the `seat` group and start/enable the `seatd.service` and you should be good to go. I suggest you to check out the Sway page in the [Arch wiki](https://wiki.archlinux.org/title/Sway#Starting) for further details.
Good luck!

**Comment by josteink** [comment]
I had this exact issue on both a previously working Ubuntu (22.10) install and a fresh Arch install. 

I can confirm the proposed solution worked on Arch.

**Comment by josteink** [comment]
Ok. So after enabling seatd I tried disabling gdm and just boot straight into the tty. 

For some reason I still got the same error as before. Seemingly I need to keep start/boot into gdm and from there on switch to the tty. 

Then sway works. No idea why it is like that, or what dependency this triggers, but just leaving it here for other people with the same issue.

**Comment by bl4ckb0ne** [comment]
Closing, as this is a distro related issue.

**Comment by suhail-akhtar** [comment]
The XDG_RUNTIME_DIR environment variable is used to specify the directory for user-specific runtime files. If it’s not set, you might encounter the error you’re seeing.
Here’s how you can set it:

export XDG_RUNTIME_DIR=/run/user/$(id -u)

To make this change permanent, you can add the above line to your .bashrc

echo "export XDG_RUNTIME_DIR=/run/user/$(id -u)" >> ~/.bashrc

source ~/.bashrc


This should resolve the XDG_RUNTIME_DIR not set issue

**Comment by Samueru-sama** [comment]
> Closing, as this is a distro related issue.

Please reopen this issue because the XDG Spec says that it can be unset: https://specifications.freedesktop.org/basedir-spec/latest/



> If $XDG_RUNTIME_DIR is not set applications should fall back to a replacement directory with similar capabilities and print a warning message. Applications should use this directory for communication and synchronization purposes and should not place larger files in it, since it might reside in runtime memory and cannot necessarily be swapped out to disk.

**Comment by emersion** [comment]
This is a "should", not a "must". Additionally, this recommendation wouldn't work for IPC, since other processes have no way to discover which replacement directory has been picked by Sway.

**Comment by Samueru-sama** [comment]
> This is a "should", not a "must". Additionally, this recommendation wouldn't work for IPC, since other processes have no way to discover which replacement directory has been picked by Sway.

sway already defaults to using `~/.config` when `XDG_CONFIG_HOME` is not set, even though that one is also a should.

Also [i3 defaults to using /tmp](https://github.com/i3/i3/blob/next/docs/ipc#L16-L20) when there is no XDG_RUNTIME_DIR. 

--------------------------------------

slightly off-topic btw pls I'm still having this other [issue](https://github.com/swaywm/sway/issues/8191) 😭

**Comment by kennylevinsen** [comment]
> sway already defaults to using ~/.config when XDG_CONFIG_HOME is not set, even though that one is also a should.

There is no problem with defaults within a single process. IPC requires *all* processes using the IPC to know and agree on the path. All application using the sway/i3 IPC libraries, `swaymsg`, `i3-msg`, etc. must all have the same default, making things more complicated.

> Also [i3 defaults to using /tmp](https://github.com/i3/i3/blob/next/docs/ipc#L16-L20) when there is no XDG_RUNTIME_DIR.

Using `/tmp` is a spec violation:

> $XDG_RUNTIME_DIR defines the base directory relative to which user-specific non-essential runtime files and other file objects (such as sockets, named pipes, ...) should be stored. The directory MUST be owned by the user, and they MUST be the only one having read and write access to it. Its Unix access mode MUST be 0700.

**Comment by kennylevinsen** [comment]
> This is also common practice

No - having one single application default for its own config file when an env var is missing is something else entirely than having an entire ecosystem of IPC clients and servers agree on what to do when the runtime dir is not specified.

> does not violate the spec as long as the dir created is 700

`/tmp` is 777 and usually owned by root, not owned by your 700 and owned by your user. If you changed that, all other uses of `/tmp` would break, so it cannot be reconciled with the requirements.

It would be different if there was a pre-agreed default like for `.config`, but other things trying `/tmp` suggests otherwise.

**Comment by Samueru-sama** [comment]
> > This is also common practice
> 
> No - having one single application default for its own config file when an env var is missing is something else entirely than having an entire ecosystem of IPC clients and servers agree on what to do when the runtime dir is not specified.

What's so different here compared to i3wm, i3-msg, etc knows to look in `/tmp/i3-***` when not using XDG_RUNTIME_DIR.

> > does not violate the spec as long as the dir created is 700
> 
> `/tmp` is 777 and usually owned by root, not owned by your 700 and owned by your user. If you changed that, all other uses of `/tmp` would break, so it cannot be reconciled with the requirements.
> 
> It would be different if there was a pre-agreed default like for `.config`, but other things trying `/tmp` suggests otherwise.

The  subdirectory in `/tmp` to put your socket can be made 700, the subdirectory part is what I know apps will do when XDG_RUNTIME_DIR is made, maybe they forget to include that when making the subdirectory but in any case that's far better than outright failing.

This is like saying that `/run/user/$UID` doesn't work because `/run/user` is owned by root

**Comment by kennylevinsen** [comment]
We're not going to create a runtime dir - create it before starting sway. [Plenty of ways to do that](https://man.sr.ht/~kennylevinsen/seatd/#xdg_runtime_dir-not-set).

**Comment by Samueru-sama** [comment]
> We're not going to create a runtime dir - create it before starting sway. [Plenty of ways to do that](https://man.sr.ht/~kennylevinsen/seatd/#xdg_runtime_dir-not-set).

No problem, also I don't use sway anyway, too many issues that you can see if you search for my user here. But this isn't a distro issue once again, it is taking the bad assumption that everyone uses elogind which sets that var and apparently that's too much work to fix?

At the very least I would like to see a message [warning about the variable not being set](https://github.com/swaywm/sway/pull/7380), because right now sway will just crash and log me out of my tty without telling me what went wrong, and also mention this in the `i3_compat.md`.

**Comment by kennylevinsen** [comment]
> also I don't use sway anyway

then why are you here?

> At the very least I would like to see a message https://github.com/swaywm/sway/pull/7380

[We already log that it is not set](https://github.com/swaywm/sway/blob/d417a8fcd0a701395c2029adade261d19800f763/sway/main.c#L276). We don’t have a preference on how to set it.

Setting the seat group and enabling seatd is *not* a solution to the runtime dir issue. The FAQ I linked gives a bunch of options as seatd users might find themselves missing the dir, but seatd never sets the var.

**Comment by kennylevinsen** [comment]
Closing as the OPs issues were resolved over a year ago.
